CREATE TABLE IF NOT EXISTS dosen (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nip VARCHAR(40) NOT NULL,
    nama_dosen VARCHAR(150) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dosen_nip (nip),
    KEY idx_dosen_nama (nama_dosen)
) ENGINE = InnoDB;
